Adding async tenant-manager write with IP+Mac of the container
plumgrid/libnetwork-plugin pull request #70
Opened 2016-10-10 03:37 UTC by eduser25

con-62, changes the way tenant_manager info is posted.
Warning: There seems to be some cleanup issue. To be debugged.

Signed-off-by: eduards <eduards@plumgrid.com>

2016-10-10 19:11 UTC, msagheer requested changes

2016-10-10 19:11 UTC, msagheer commented on plugin/driver/network_utils.go
> +		if strings.HasPrefix(ifc.ifc_name, pg_prefix) {
This logic will break in case we have multiple interfaces, as every time for very first interface we will enter into this if condition and the information will be posted with same mac address and IP

2016-10-10 19:11 UTC, msagheer commented on plugin/driver/network_utils.go
> +		for _, ifc := range ifc_list {
This is redundant, as we are doing the same in RunContainerArping where we enter the namespace and fetch the address to generate the ARP. I would suggest rather having two separate go routines accessing information separately should be unified.

2016-10-10 19:47 UTC, eduser25 commented on plugin/driver/network_utils.go
> +		for _, ifc := range ifc_list {
I somehow agree but, you will mess up the context of each one and end up with a huge function doing several stuff, which is unadviced. Right now it clearly separates the two routines: one does one job, the other one the other.

Additionally, even though the information used is more or less the same, the operations done on arping are inside the namespace, whilst the metadata write has to be done outside. This is only my way of seeing it, if you guys still think to merge both, we can do.

2016-10-10 19:50 UTC, eduser25 commented on plugin/driver/network_utils.go
> +		if strings.HasPrefix(ifc.ifc_name, pg_prefix) {
? the mac address is not given from cnm but read from the IFC itself, which every ifc has its own. Check the structure being traversed.

Regardless, check the comment below on the code, we don't have a way to identify the name of the interface inside the container; I can only return all the interfaces inside the container and we can as much as post the information for one, or all of them. 

Edit: actually i'm wrong. We do have the mac inside (no?) of the container, so maybe we can map and guess which interface we want the information for. I'll ping you for some chat.

2016-10-13 11:46 UTC, closed without merging

2016-10-14 06:50 UTC, msagheer commented on plugin/driver/pg_helper.go
> +						"ip_address": "` + ip + `",
same change needed in above condition as well, in case of multiple interfaces IP won't be updated.